### PR TITLE
Compute pycnocline depth and thickness

### PR DESCRIPTION
**Pull request by jpolton**
Added two pycnocline variables: depth and thickness.

Depth moments of stratification are used as proxies for pycnocline depth (as the first  moment of stratification), and pycnocline thickness  (as the 2nd moment of stratification). This approximation improves towards the limit of a two-layer fluid.   
For stratification that is not nearly two-layer, the pycnocline thickness appears large and this method for identifying the pycnocline breaks down.

I've added an ``example_scripts/internal_tide_pycnocline_diagnostics.py`` that does a bit more than the unit testing: looks at transect plots, shows what happens when the fluid is not two layers, make a nicer map plot.

AC: 
- [ ] unit testing - it works?
- [ ] ``example_files/internal_tide_pycnocline_diagnostics.py``   - it works? (I run it in spyder block by block, or with ``ipython run example_scripts/internal_tide_pycnocline_diagnostics.py`` command)

I am not sure that the name ``DIAGNOSTICS.py`` is right. It might be better as ``INTERNALTIDE.py`` in a folder called ``DIAGNOSTICS`` and perhaps living alongside  ``CEOF.py``, ``TRANSECT.py``, ``CRPS.py`` science thingies. Tom might not like that though. I will leave it as is for now and create a ticket to mull over it. https://github.com/British-Oceanographic-Data-Centre/COAsT/issues/141

Also I am not sure about my choice of variables names. I create variables ``self.dataset.pycno_depth`` and ``self.dataset.pynco_thick`` when they are really ``strat_1st_moment`` and ``strat_2nd_moment``. Though the former is more intuitive it is only really true for two-layer density structures. Thoughts? (I suspect it doesn't matter)

### CODE REVIEW

**Comment by jpolton** [comment]
> 1. Unit test runs with no problems.
> 2. The example internal_tide script doesn't. For me there is an initial error at line 117:
> 
> ```
> AttributeError: 'Dataset' object has no attribute 'rho_dz
> ```
> 
> This error carries over to some future plotting bits of the script.
> 
> 1. For the name of the object: I think it depends on what the future for it is. If its application is going to stay roughly similar as it is now, then maybe INTERNALTIDE or STRATIFICATION might be better.
> 2. Variable naming: I think either set of names is fine, so long as it is clear in the documentation what is meant by them. Maybe to avoid confusion, the variables should be named properly (`strat_moment_1` or whatever) and then the docstring can say that 'in a 2 layer fluid these are equivalent to...'.

@davbyr Hmm. Which machine were you running this on? Can you copy the entire screen dump of output please?

**Comment by davbyr** [comment]
@jpolton For whatever reason, upon reopening Spyder the script works fine this morning.

**Review by anwiseNOCL — APPROVED** [review]
Unit test worked without error except I noticed that item 3c does not print a message so I think something is not quite right because it should print an OK if the calculation is good.
The Diagnostic scripts also worked. Nice plots.

With the naming. Maybe the file should be INTERNALTIDE.py because I suppose a lot of the code here could be considered diagnostics. Not sure about the other naming issue. Maybe the less intuitive with good documentation?

**Comment by jpolton** [comment]
@anwiseNOCL @davbyr following your suggestions:

*  I changed the pycnocline variable names from `pycno_depth` and `pycno_thick` to `strat_1st_mom` and `strat_2nd_mom` and fleshed out the doc string some more to describe the limiting case for a 2-layer fluid.

* I changed the class name from DIAGNOSTICS to INTERNALTIDE.

The AC still work for me on my mac and livljobs8 so I assume that all the changes are consistent with that which worked for you.

I couldn't reproduce @anwiseNOCL issue with unit_test.py 3c not having a print statement. We can pick that up later.

**Pull request merged**
