### PR TITLE
Tutorial scripts added and small bug fix in TIDEGAUGE

### PR DESCRIPTION
**Pull request by davbyr**
@jpolton @anwiseNOCL  I've added two tutorial scripts to example_scripts:

tidegauge_tutorial.py
altimetry_tutorial.py

They both just show off what the two objects do and how to use them.

I also found a very small bug in TIDEGAUGE.py's plot_on_map_multiple(), which I fixed. Completely up to you if you want to review it or not.

### CODE REVIEW

**Review by jpolton — CHANGES_REQUESTED** [review]
Thanks Dave.
A thought: since the Lowestoft gauge's nearest neighbour model point is in land it might be useful to mask the model variable with the _new_ bathymetry variable applying the search. An enhancement perhaps? Not had a chance to investigate as busy with talk prep.

**Review by jpolton — APPROVED** [review]

**Comment by jpolton** [comment]
I was thinking something like:
```
nemo.dataset['masked_ssh']= nemo.dataset['ssh'].where( nemo.dataset['bathymetry']> 10)
tidegauge.obs_operator(nemo, mod_var_name='masked_ssh', time_interp='nearest')
tidegauge.dataset.interp_masked_ssh.plot()
```
But it doesn't work for me..

**Comment by davbyr** [comment]
@jpolton This is a good point. That method won't work because the longitudes and latitudes need to also be masked. So you could apply that same step to those variables too. Obs_operator() looks for longitude and latitude so:

```
nemo.dataset['latitude']= nemo.dataset['latitude'].where( nemo.dataset['bathymetry']> 10)
nemo.dataset['longitude']= nemo.dataset['longitude'].where( nemo.dataset['bathymetry']> 10)
```

Having said this, I don't have any problem with using obs_operator for Lowestoft. I have noticed that in the test script, the data looks flat because it's comparing 2 days of high frequency tide gauge data to model data thats on a 5-day frequency. For a proper test, the model data needs to be higher frequency too. 

Your point is still good though and some kind of masking should be available when using obs_operator. I'll think of how best to do it.

**Review by anwiseNOCL — APPROVED** [review]
This is useful to have. Is it intended to be an extension of the online documents?

**Pull request merged**
