### PR TITLE
0104 grid attrib

### PR DESCRIPTION
**Pull request by jpolton**
If data is loaded in a one-liner: ``sci = coast.NEMO(dn_files + fn_nemo_dat)``
Then variables are renamed to standard (set in NEMO.py)
Dimensions are relabelled to standard  (set in NEMO.py)  as {t_dim, z_dim, y_dim, x_dim}
And ``grid_ref`` is set as an attribute (defined in NEMO.py), e.g. "t-grid"

AC:
1. ``run unit_testing/unit_test.py`` works
2. We are happy with this course of action.

NB if you load the data the slow method:
```
ds = xr.open_dataset(dn_files + fn_nemo_dat)
sci_load_ds = coast.NEMO()
sci_load_ds.load_dataset(ds)
```
it doesn't automatically do these changes. This may or may not be a good thing?

### CODE REVIEW

**Comment by anwiseNOCL** [comment]
@jpolton The grid ref attribute mapping is confusing me a bit. Are we assigning a grid ref attribute to each variable? I thought we were going down the route of different nemo objects for each grid? Maybe i misunderstood.

**Comment by jpolton** [comment]
> @jpolton The grid ref attribute mapping is confusing me a bit. Are we assigning a grid ref attribute to each variable? I thought we were going down the route of different nemo objects for each grid? Maybe i misunderstood.

Ah! Yes. Hmm. It is an open question.
* Your transect work does lend itself to grouping by grid as you load in lots of variables. --> group by grid makes sense.
* What should happen if we created a new object (e.g. d(SSH)/dx from the t-grid onto the u-grid)? Should that new variable to placed into a u-grid dataset, or should it sit in the object with its parent? 
* What about the observations? @davbyr is there logic for grid_ref by DataSet or DataArray?

**Comment by davbyr** [comment]
For me, grid ref is just a way to connect up variables with coordinates. So for observations, grid_ref isn't really relevant as an observation object contains both lon/lats and variables, which are assumed to correspond with each other. For the NEMO object, I see the grid_ref attribute as being useful in the case of a single DOMAIN object. If we're putting the relevant coordinate and time information into the NEMO object with the variables then this might only be used at initialisation to determine which coordinates to pull across.

So any given object would contain its data and corresponding coordinates/time, perhaps standardised to longitude, latitude and time (as is the case for observations). If new variables are being created (e.g. gradient), I think that should go into the object that contains its grid information (so the u-grid object in your example). Or it goes into its own brand new dataset.

Short: I think the most flexible and consistent way to do it is to have a grid_ref attribute per object, and everything inside that object adheres to it.

**Comment by davbyr** [comment]
Let me expand a bit... Maybe we should only have a NEMO object accessible to the user, which is initialised as:

```
sci = coast.NEMO(fn_data, fn_domain, grid_ref)
```
Upon initialisation, the object loads in the data and domain files, but then uses grid_ref to pull over the relevant coordinates and renames them without the U/V/T suffixes (longitude/latitude/time, e3 etc). These could either go into the same dataset as the variables or could be stored inside a 'grid' dataset. The point is that the object now only holds the relevant grid info for the variables inside it, which can be accessed easily with, e.g. sci.dataset.longitude or sci.dataset.e3. 

This would be consistent across all objects (including observations and in future other models), with no need to specify grid. I think this is useful for understandability by the user.

If no domain/grid_ref is specified then it simply renames what it can (maybe just nav_lat, nav_lon) and some routines will just not be useable (Transect).

The one downside to this is the multiple loading of grid information, which we discussed on Tuesday. I don't think this would be a big problem though, since for a given set of NEMO data, no grid varaible would be loaded more than once (I think). If there are multiple NEMO files, then the standard should be to concatenate them along time, then no grid information would be reloaded. In the one case of ensembles (which Jeff mentioned), I don't think we should worry about it for the time being and would suggest a different NEMO_ENS object for this, which would load in the grid once.

**Comment by anwiseNOCL** [comment]
I think I agree with all that. So when you create a nemo object, you tell it which grid it is and then a method will pull all the relevant stuff from domain into it's dataset attribute. New variables created will need to go in the object with the correct grid I think, because suppose in your example you wanted to perform a 2nd derivative, you would need the correct grid then. This has the advantage of being very transparent for developers and users.

**Comment by jpolton** [comment]
I think that we are all agreed that this is the way forward. I think that there are 3 parts to this:

**DataSet grid_ref tagging**: I've updated this [ticket](https://github.com/British-Oceanographic-Data-Centre/COAsT/issues/104) with the grid ref requirements.

**coords/dims renaming**: I've updated this [ticket](https://github.com/British-Oceanographic-Data-Centre/COAsT/issues/106) with the variable naming requirements.

**Loading** data from [specified grid](https://github.com/British-Oceanographic-Data-Centre/COAsT/issues/107)

I've copied and pasted your comments into these separate tickets. Hopefully the fragmentation makes it easier rather than harder!

Since they are inter-linked I suggest keeping the remote repo up to date.
I suggest starting from this branch [0104_grid_attrib](https://github.com/British-Oceanographic-Data-Centre/COAsT/tree/0104_grid_attrib), which is close to develop and only with relevant changes.

Any takers?

**Comment by davbyr** [comment]
I'll give it a go now

**Comment by davbyr** [comment]
I've had a crack at this, although it wasn't as straightforward as I was suspecting. There were some problems with flexibility and ensuring that there were no overlaps between the domain/data datasets when merging (time_counter is in both for example, and there is the different time dimension in domain). Here's how my changes should work:

1. DOMAIN no longer needs to be called and is redundant in this branch.
2. NEMO is created with file arguments for the data and domain.
3. If no domain file is provided, it loads and warns the user than functionality is limited.
4. grid_ref needs to be specified on initialisation, by default it is 't'. Case independent.
5. NEMO has it's own init routine, so files must be provided on creation. I'm sure this can be changed if necessary.
6. NEMO data reads in the data file as before and renames vars/dims.
7. The DOMAIN file is read into a temporary dataset. It's dimensions are first renamed. The required variables are then pulled into a temporary dummy dataset. Variables inside this dataset are renamed BEFORE merging into the object dataset.
8. domain renaming dictionaries are set in `set_dimension_mapping` and `set_variable_mapping`. They are used in `merge_domain_into_dataset()`.

Notes:
1. I can't figure out if this preserves lazy loading or not...
2. This all makes heavy use of xarray.merge().
3. Variable renamings are not necessarily right, jsut wanted to get it working. 
4. Unit testing does not work because I have not updating anything else.

What it looks like:

```
sci = coast.NEMO(fn_data, fn_dom, grid_ref='t')
```
The dataset looks like:
```
<xarray.Dataset>
Dimensions:              (axis_nbounds: 2, t_dim: 7, t_dim0: 1, x_dim: 297, y_dim: 375, z_dim: 51)
Coordinates:
    deptht               (z_dim) float32 3.038086 9.3671875 ... 5822.174
    nav_lat              (y_dim, x_dim) float32 ...
    nav_lon              (y_dim, x_dim) float32 ...
    time                 (t_dim) datetime64[ns] 2007-01-01T11:58:56 ... 2007-01-31T11:58:56
    time_instant         (t_dim) datetime64[ns] ...
Dimensions without coordinates: axis_nbounds, t_dim, t_dim0, x_dim, y_dim, z_dim
Data variables:
    deptht_bounds        (z_dim, axis_nbounds) float32 ...
    sossheig             (t_dim, y_dim, x_dim) float32 ...
    time_counter_bounds  (t_dim, axis_nbounds) datetime64[ns] ...
    temperature          (t_dim, z_dim, y_dim, x_dim) float32 ...
    glam                 (t_dim0, y_dim, x_dim) float32 ...
    gphi                 (t_dim0, y_dim, x_dim) float32 ...
    e1                   (t_dim0, y_dim, x_dim) float32 ...
    e2                   (t_dim0, y_dim, x_dim) float32 ...
    e3_0                 (t_dim0, z_dim, y_dim, x_dim) float32 ...
    e3vw_0               (t_dim0, z_dim, y_dim, x_dim) float32 ...
    time0                (t_dim0) float32 ...
    jpiglo               float32 ...
    jpjglo               float32 ...
    jpkglo               float32 ...
    jperio               float32 ...
    ln_zco               float32 ...
    ln_zps               float32 ...
    ln_sco               float32 ...
    ln_isfcav            float32 ...
```

**Comment by anwiseNOCL** [comment]
@davbyr @jpolton Just a quick comment as not gone through it yet but by default I don't think merge will preserve lazy loading because it needs to compare data for conflict. Having said that it may only do that on variables that have the same name in both dataset. There should be an option under kword compat to turn this off. Another approach might be to add the dataarrays from domain into the dataset manually then perhaps we could remove that time0 dimension in the process which is pretty pointless as far as i can tell.

**Comment by davbyr** [comment]
Yeah I suspected it wasn't presrving lazy loading. What is manual adding of dataarrays? `xarray.assign()`? 

I'm happy to have time0 removed -- for now this was just getting the structure set up.

**Comment by jpolton** [comment]
I just suggested a few changes to explicitly include the new variables into the NEMO object. Given that all the DataArrays we are assigning are new to the NEMO object then they can surely just be directly placed.

**Comment by anwiseNOCL** [comment]
@davbyr I was thinking something along the lines of. I assume this doesn't load the data, not 100% of that though...
```
NEMO_u.dataset['e3_0'] = domain.dataset.e3u_0.squeeze()
```

**Comment by jpolton** [comment]
Regarding @davbyr point 3. "Variable re-namings are not necessarily right, jsut wanted to get it working."

With xarray there is a difference between variables and coordinates. Presently the nemo data file, on loading does distinguish between coords and variables, but the domain_cfg.nc file loads with only variables

We want to make sure the renaming of "variables" like ``glam`` puts them as coordinates. Maybe this is  https://github.com/British-Oceanographic-Data-Centre/COAsT/issues/106

**Comment by jpolton** [comment]
> @davbyr I was thinking something along the lines of. I assume this doesn't load the data, not 100% of that though...
> 
> ```
> NEMO_u.dataset['e3_0'] = domain.dataset.e3u_0.squeeze()
> ```

I thought there might be an advantage of e3t_0 having a time stamp at the first time step, but no the time variable is just zero.
I agree we should purge it from the domain_cfg.nc files. Squeeze works well.

**Comment by davbyr** [comment]
I've streamlined the code a little (hopefully, all old code still there and commented). Also squeezed the dataarrays so time0 is gone.

Also, thats a good point about the coordinates @jpolton and something I keep forgetting about.

**Comment by jpolton** [comment]
I've added a variant of @anwiseNOCL depth_depths code following the load_domain. I've then added depth_0 to the list of "merged" variables and replaced the 1D coordinate ``deptht`` with ``depth_0``

To achieve this I move the set_dimension_names action on the dataset_domain to happen on load

**Comment by davbyr** [comment]
Sounds good @jpolton . I think we need to get to a point with this branch where we are happy with the basic load -> rename -> assign -> process flow and can either put it into develop or start making branches of this branch. For example the methods in DOMAIN will need to be moved over to NEMO and then the CRPS stuff will need to be changed to account for the lack of DOMAIN object. We probably shouldn't be continuing to make changes directly to the same branch.

I'm happy with how this is working now. If we three are all happy, I'd suggest we fix this branch in place and create branches off of it until unit testing works again. (or we can put it in develop now if we're not too bothered about develop 'working').

**Comment by davbyr** [comment]
@jpolton @anwiseNOCL This branch has now had Ant's most recent branch merged into it. Some testing suggests the loading is all working OK. I will branch this branch and fix the CRPS stuff for the new structure. 

I've also moved some things from DOMAIN into COAsT, but not everything. The remaining methods are things that I don't use, so you two might want to take a look and see what needs keeping/moving/deleting.

**Comment by jpolton** [comment]
> @jpolton @anwiseNOCL This branch has now had Ant's most recent branch merged into it. Some testing suggests the loading is all working OK. I will branch this branch and fix the CRPS stuff for the new structure.
> 
> I've also moved some things from DOMAIN into COAsT, but not everything. The remaining methods are things that I don't use, so you two might want to take a look and see what needs keeping/moving/deleting.

Hmmm the load methods break when I try unit_test.py on this branch...
```
    103 ds = xr.open_dataset(dn_files + fn_nemo_dat)
--> 104 sci_load_ds = coast.NEMO()
    105 sci_load_ds.load_dataset(ds)
    106 sci_load_file = coast.NEMO()

TypeError: __init__() missing 1 required positional argument: 'fn_data'
```
@davbyr do you have some edits to the load methods that you can push back, that are distinct from the CRPS fixes?

**Comment by davbyr** [comment]
@jpolton it is still expecting at least a NEMO data file. I had updated unit testing to test this but apparently I didnt commit that file..

I havent added the functionality allowing for just a domain to be loaded yet. I figured that would be it's own branch and ticket. This is what works:

```
Nemo = NEMO.load(fn_dat, fn_dom, grid_ref)
```

**Comment by anwiseNOCL** [comment]
@davbyr @jpolton I need domain only functionality so i will take a look at adding in the option to add no data.

**Comment by jpolton** [comment]
@anwiseNOCL @davbyr 
To get the unit_test.py file to skip the problems  I am not interested in I used:
```
try:
    subsec = subsec+1
    <stuff wot woz there>
except:
    print(str(sec) + chr(subsec) +" FAILED")
```

I was planning on sorting out some of those indices. But I can see this becoming a bit of a mess....
Fancy converging on the MSML teams group (actually the Tea drop in slot) at 3pm to confer?

**Pull request merged**
