### PR TITLE
Feature/SE-NEMO_jp --> SE-NEMO

### PR DESCRIPTION
**Pull request by jpolton**
Things done:

* rename `experiments.py` --> `experiments_file_handling.py`
* Move `experiments_file_handling.py` to `_utils/`
* A couple of minor typos fixed

The dependency packages `xesmf` and `esmpy` are for regridding. Last sprint we decided that perhaps they ought not to be in the main package, as this can create problems if there are too many dependencies.
This means it would be up to the user to conda/pip install them if they want them. Maybe this needs better sign posting.

Note, like the SE-NEMO branch this seems to fail some pytesting in the `tests/test_climatology.py` git action. Didn't get to dig into it.

### CODE REVIEW

**Comment by anwiseNOCL** [comment]
@jpolton Been on a bit of a journey tracking down an error i get with unit testing.  Turns out there is a new file
"tide_gauges/liverpool_gladstone_dock-liv-gbr-bodc" which I don't have. This is not in the examples files I suppose because you just added it? Could you point me to it and i'll grab a copy for Jasmin

**Comment by anwiseNOCL** [comment]
Other than that it makes sense to me.

**Comment by jpolton** [comment]
Ah yes. It is here `/projectsa/COAsT/files_upd_jun22/tide_gauges/liverpool_gladstone_dock-liv-gbr-bodc`

**Review by anwiseNOCL — APPROVED** [review]
This all works now for me and seems sensible.

**Review by jasontempestholt — APPROVED** [review]
all look fine to me

**Pull request merged**
