### PR TITLE
0070/isobath contour

### PR DESCRIPTION
**Pull request by anwiseNOCL**
@jpolton @davbyr This pull request adds in an CONTOUR module with a Contour class and Contour_f and Contour_t class that inherit from Contour. These child classes are instantiated with only the NEMO object that correspond to their respective grids. Methods within those classes that require information from the other grids must have those NEMO passed in as parameters. I will update TRANSECT to follow the same design.

NOTE it requires the import:
`from skimage import measure`
So you will need the skimage package and this will need to be added to the COAsT package

**How things work**
Creation of a contour object requires the model y and x indices that define the isobath contour to be passed in. The user may already have the indices, but if not, there are 3 static class methods to help the user obtain these indices in a robust way.

1. `Contour.get_contours(nemo: COAsT, contour_depth: int)`
is a very efficient method for extracting the continuous contours for a supplied depth within the domain. The method returns a list of all the continuous contours within the domain.
2. `Contour.plot_contour(nemo: COAsT, contour: np.ndarray)`
is simple quick plot method which overlays the desired contour on the model bathymetry.
2. `Contour.get_contour_segment(nemo: COAsT, contour: np.ndarray, start_coords, end_coords)`
allows the user to extract a segment from a contour defined between two sets of coordinates.

For example 
```nemo_f = coast.NEMO( fn_domain=dn_files+fn_nemo_dom, grid_ref='f-grid' ) 
# find 'continuous' 200m isobath contours
contours, number_of_contours = coast.Contour.get_contours(nemo_f, 200) 
# plot first one
coast.Contour.plot_contour(nemo_f, contours[0]) 
# extract segment from it
y_ind, x_ind, contour = coast.Contour.get_contour_segment(nemo_f, contours[0], [50,-10], [60,3]) 
# check it again
coast.Contour.plot_contour(nemo_f, contour) 
 # happy, create contour object
cont_f = coast.Contour_f(nemo_f, y_ind, x_ind, 200)
```
When a contour object is created the dataset is subsetted into a Contour.data_contour dataset.

From Contour_t, the user can calculate the 3d (time, depth, along-contour) perturbation pressure and insitu density.
From Contour_f the user can calculate the 3d cross-contour flow and volume transport, as well as the components of these velocities and transports due to the hydrostatic and surface pressure gradients. Note that these quantities are defined on the normal velocity points i.e. the points between the f-points, and the variables are stored in the Contour_f.data_cross_flow dataset.

**Other stuff**

- I have not added any fancy plotting routines to Contour at this time.

- I have not added any logging yet.

- I added a 'bathymetry' variable which is created when the Nemo object is created. This gives the bathymetry at each (y,x) point for whatever horizontal grid the Nemo object is. 

- Should close tickets #70 #64

### CODE REVIEW

**Review by jpolton — COMMENTED** [review]
``conda install scikit-image``
...
In spyder:
```
run unit_testing/unit_test.py
```
Everything worked fine until:
```
...
7a OK - Altimetry quick plot saved
8b OK - Tide gauge map plot saved
8c OK - Tide gauge time series saved
Traceback (most recent call last):

  File "/Users/jeff/GitHub/COAsT/unit_testing/unit_test.py", line 846, in <module>
    contours, no_contours = coast.Contour.get_contours(nemo_f, 200)

  File "/Users/jeff/GitHub/COAsT/coast/CONTOUR.py", line 46, in get_contours
    contours = measure.find_contours( nemo.dataset.bathymetry, contour_depth )

  File "/Users/jeff/anaconda3/envs/coast_env/lib/python3.7/site-packages/skimage/measure/_find_contours.py", line 136, in find_contours
    fully_connected == 'high', mask=mask)

  File "skimage/measure/_find_contours_cy.pyx", line 19, in skimage.measure._find_contours_cy._get_contour_segments

  File "stringsource", line 658, in View.MemoryView.memoryview_cwrapper

  File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__

TypeError: a bytes-like object is required, not 'DataArray'
```

@anwiseNOCL : Did I do the correct ``conda install``?

**Comment by anwiseNOCL** [comment]
> run unit_testing/unit_test.py
@jpolton I can't reproduce that, but it looks as though the method being called won't accept a DataArray. Which version of scikit-image have you installed? It works for me with versions 0.15 and 0.16.1. I just looked at the api doc and it seems they have changed the method signature in the latest version. Maybe you have that. I will try to reproduce.

**Comment by jpolton** [comment]
@anwiseNOCL  Unit testing all works for me. The bathymetry variable will be very useful.

**Review by davbyr — APPROVED** [review]
Works for me. All looks very cool

**Pull request merged**
