### PR TITLE
Some general changes

### PR DESCRIPTION
**Pull request by davbyr**
Some smaller changes here and there, listed below:

1. CDF() Class removed/replaced with DISTRIBUTION class. This is just somewhere to keep some of the old methods for creating/storing distribution data. Previous CRPS related things in here are now in crps_util (already there). No new unit testing required, only existing tests. Old change from apply_crps.
2. Some changes to PROFILE(). Read_EN4 expanded to read multiple EN4 files. EN4 files don't contain any dimension along which xarray can do automatic concatenation, therefore open_mfdataset() doesn't seem to work. read_EN4() can read multiple en4 files, assuming that the files are named as downloaded, with dates.
3. crps_empirical moved to crps_util. This is the general CRPS routine. Old change from apply_crps.
4. Some unneeded routines removed from crps_util (they are already in General_utils. Old change from apply_crps.
5. create_geo_axes() added to plot_util. This is for creating an 'empty' geographical plot using cartopy. Will plot coastlines and return the figure and axis object. Scatter/pcolor/other can then be added to this, as per the example in the docstring. New tests in unit_test with saved plot.
6. Two utility routines added to plot_util: determine_colorbar_extension() and determine_clim_by_standard_deviation(). The first is for automatically determining whetehr a colorbar needs extend='both','max','min' or 'neither. The second is for determining color limits ignoring outliers. New tests in unit_test.
7. scatter_with_fit() added to plot_util. This is a routine for scatter plotting data and automatically including a linear fit, with R2 information. New test in unit_test with saved plot.

Also unit_test updated so that example scripts are always last in a section-N.

### CODE REVIEW

**Comment by davbyr** [comment]
Thanks @jpolton . I hadn't pushed some of the final changes for unit testing. Unit testing should work now and there is a few new tests for some of the plotting utilities.

**Review by anwiseNOCL — CHANGES_REQUESTED** [review]
I'm still getting some issues with the profile stuff on livljobs:

11a FAILED.
11b OK - Profiles map plot saved
11c FAILED.
11d FAILED.
12a OK. Scatter_with_fit()
12b OK. create_geo_axes()
12c OK - determine_colorbar_extension()
12d OK - determine_clim_by_std_dev

also the profile stuff needs to be copied over to the unit_test_contents.txt

**Comment by davbyr** [comment]
Thanks @anwiseNOCL . Works for me, I'll look into it

**Comment by davbyr** [comment]
@anwiseNOCL My Spyder was pointing at the wrong COAsT branch and was testing the PROFILE stuff from a very similar branch. Restarted Spyder and it found a problem with a dimension name in PROFILE (N_PROF is now profile). Fixed and it ran fine for me now. Sorry about that.

**Review by jpolton — APPROVED** [review]
All works fine now, locally.
I would however change the example_scripts testing from Section X to Section 0 or Section N (keeping it at the end) as the X looks like a fail:

```
X. Example script testing
++++++++++++++++++++++++
load and plot HLW data
Try the TIDEGAUGE.show() method:
time (Europe/London): Tue 2020-10-13T03:13+0100 height: 2.8 m
time (Europe/London): Tue 2020-10-13T08:59+0100 height: 8.01 m
time (Europe/London): Tue 2020-10-13T15:36+0100 height: 2.83 m
time (Europe/London): Tue 2020-10-13T21:21+0100 height: 8.45 m
Try the TIDEGAUGE.get_tidetabletimes() methods:
LT: 2.83 m at 2020-10-13T14:36:00.000000000
HT: 8.01 m at 2020-10-13T07:59:00.000000000
HT: 8.01 m at 2020-10-13T07:59:00.000000000
Xa OK - tutorials on example_files data
Don't forget to test on a LIVLJOBS machine
X X - example_scripts failed on LIVMAZ
```

**Comment by davbyr** [comment]
@jpolton Good point, changed

**Review by anwiseNOCL — APPROVED** [review]

**Comment by anwiseNOCL** [comment]
@davbyr all good!

**Pull request merged**
