### PR TITLE
0026/eof

### PR DESCRIPTION
**Pull request by anwiseNOCL**
eof module added that includes two functions:
1. Allows the user to compute regular EOFs, the associated temporal projections and the variance explained by each mode.
2. Allows the user to compute complex Hilbert EOFs, the associated temporal projections and the variance explained by each mode.

Like some of the other stats functions, these methods are not tied to NEMO model data and there isn't much need for a class structure either (at least currently) so these are simple module functions:
```
heofs = coast.hilbert_eofs( nemo_t.dataset.ssh )
heofs
Out[2]: 
<xarray.Dataset>
Dimensions:         (mode: 7, t_dim: 7, x_dim: 297, y_dim: 375)
Coordinates:
  * mode            (mode) int64 1 2 3 4 5 6 7
    longitude       (y_dim, x_dim) float32 -19.888672 -19.777344 ... 13.0
    latitude        (y_dim, x_dim) float32 40.066406 40.066406 ... 65.00098
    time            (t_dim) datetime64[ns] 2010-01-01T12:00:00 ... 2010-01-07T12:00:00
Dimensions without coordinates: t_dim, x_dim, y_dim
Data variables:
    EOF_amp         (y_dim, x_dim, mode) float64 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0
    EOF_phase       (y_dim, x_dim, mode) float64 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0
    temporal_amp    (t_dim, mode) float64 18.39 9.522 ... 4.118e-15 3.128e-15
    temporal_phase  (t_dim, mode) float64 180.0 180.0 0.0 ... 57.38 111.1 -86.89
    variance        (mode) float64 57.99 27.12 14.88 ... 1.112e-29 1.191e-30
```
They return an xarray dataset that contains the EOFs, projections and variance as DataArrays. Also the functions will pull across the relevant coordinates from the original data variable time series so it is easy to then plot stuff using xarray.

### CODE REVIEW

**Review by jpolton — COMMENTED** [review]
Move the unit testing to 9. The script testing is liable to break stuff/patience so should come at the end.

**Comment by jpolton** [comment]
@anwiseNOCL Things are not as one would hope. Numbering off because it is not here executed in turn:
```
runcell('---------------------------------------------------------------------------#, #1', '/Users/jeff/GitHub/COAsT/unit_testing/unit_test.py')
1a X - EOF, projections or variance not as expected
/Users/jeff/anaconda3/envs/coast_env/lib/python3.7/site-packages/xarray/core/nanops.py:142: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)

runcell('---------------------------------------------------------------------------#, #2', '/Users/jeff/GitHub/COAsT/unit_testing/unit_test.py')
1b X - HEOF, projections or variance not as expected
/Users/jeff/anaconda3/envs/coast_env/lib/python3.7/site-packages/xarray/core/nanops.py:142: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)
```

Nothing helpful in the ``unit_test.log`` file either.

**Comment by anwiseNOCL** [comment]
@jpolton would you mind running them both again and printing out all the cksums and post here or send to me so I can see where it is off? thanks

**Comment by anwiseNOCL** [comment]
@jpolton @davbyr Ok I fixed the issue by putting in a better test and put this item in the unit testing before the example script testing.

**Review by jpolton — COMMENTED** [review]
Is this as expected:
```
...
8e OK - Cross-contour geostrophic flow calculations as expected
/Users/jeff/anaconda3/envs/coast_env/lib/python3.7/site-packages/xarray/core/nanops.py:142: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)
9a OK - Original signal reconstructed from EOFs
/Users/jeff/anaconda3/envs/coast_env/lib/python3.7/site-packages/xarray/core/nanops.py:142: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)
9b OK - Original signal reconstructed from HEOFs
10. Example script testing
...
```

**Comment by anwiseNOCL** [comment]
> Is this as expected:
> 
> ```
> ...
> 8e OK - Cross-contour geostrophic flow calculations as expected
> /Users/jeff/anaconda3/envs/coast_env/lib/python3.7/site-packages/xarray/core/nanops.py:142: RuntimeWarning: Mean of empty slice
>   return np.nanmean(a, axis=axis, dtype=dtype)
> 9a OK - Original signal reconstructed from EOFs
> /Users/jeff/anaconda3/envs/coast_env/lib/python3.7/site-packages/xarray/core/nanops.py:142: RuntimeWarning: Mean of empty slice
>   return np.nanmean(a, axis=axis, dtype=dtype)
> 9b OK - Original signal reconstructed from HEOFs
> 10. Example script testing
> ...
> ```

It is, those warnings are from the unit test not the EOF routines (I remove the mean from the ssh variable). For some reason xarray always raises a warning when a mean is taken over an all-NaN slice. Or maybe it is numpy that does.

**Review by davbyr — APPROVED** [review]
@anwiseNOCL Tested and all works/looks good

**Pull request merged**
