### PR TITLE
WIP: updating tidegauge_validation_tutorial.py with new Tidegauge() a…

### PR DESCRIPTION
**Pull request by jpolton**
> demean_timeseries() working.
> Profile validation scripts updated and added to `COAsT/example_scripts/profile_validation`
> Tidegauge validation scripts updated and added to `COAsT/example_scripts/tidegauge_validation`

### CODE REVIEW

**Comment by davbyr** [comment]
@jpolton I'll take a look at this this morning. The Profile validation script will also need some updating so will get that done too ASAP

**Comment by jpolton** [comment]
@anwiseNOCL check the profile bits

**Comment by jpolton** [comment]
@anwiseNOCL check the profile bits

**Comment by jpolton** [comment]
@davbyr The `tganalysis.calculate_non_tidal_residuals()` method produces a tidegauge object with 3 dimensions: `id_dim`, `port` and `time`. Is `port` really intended?

E.g. line 92 in `tide_validation_tutorial.py`
```
ntr_mod = tganalysis.calculate_non_tidal_residuals(model_new.dataset.ssh, tide_mod.dataset.reconstructed)
```
Returns an object that looks like:
```
ntr_mod.dataset
Out[70]: 
<xarray.Dataset>
Dimensions:    (t_dim: 8736, port: 61, id_dim: 61)
Coordinates:
    time       (t_dim) datetime64[ns] 2010-01-01 ... 2010-12-30T23:00:00
    site_name  (port) object 'Harwich' 'Mumbles' 'Ullapool' ... 'N/A' 'N/A'
Dimensions without coordinates: t_dim, port, id_dim
Data variables:
    ntr        (id_dim, t_dim, port) float64 nan nan nan nan ... nan nan nan nan
```

**Pull request merged**
