### PR TITLE
Feature/bodcdmsys 3636 3716 3717

### PR DESCRIPTION
**Pull request by qtl-bodc**
Rob has already done some code review here
https://github.com/British-Oceanographic-Data-Centre/COAsT/pull/315

But I have switched to push directly to the main repo (as suggested by Matt) hence this pull request.
 
@jpolton @davbyr , I have provided a test file, see tests/test_index_classes_load_datasets.py which demo's loading of the various datasets with and without a configuration file. The dataset files used in the test come from the erddap link https://linkedsystems.uk/erddap/files/COAsT_example_files/ and the network drive /projectsa/IMMERSE/WP8/TestData/ and https://www.bodc.ac.uk/data/bodc_database/gliders/

There is a json config file provided for each test in the folder config/ which are used to demo the renaming of variables and setting coordinates. Note though, the target variable name  in the mappings may not be correct.

### CODE REVIEW

**Comment by davbyr** [comment]
@qtl-bodc I've had a play with the example file and it looks good. Where is the glider file that this uses?

**Comment by qtl-bodc** [comment]
@davbyr , sorry forgot to mention , its https://linkedsystems.uk/erddap/files/Public_Glider_Data_0711/Doombar_20210214/Doombar_553_R.nc

More gliders at downloadable at https://www.bodc.ac.uk/data/bodc_database/gliders/

**Review by jpolton — APPROVED** [review]
Added short script to `example_scripts` to test the new indexed class (probably temporary until we sort out supporting www documentation and update other scripts):

```
"""
This is a demonstration script for using the INDEXED class in the COAsT
package. This object has strict data formatting requirements, which are
outlined for various (observational) data types.
"""

import coast 

dir = "/projectsa/IMMERSE/WP8/TestData/"

altimetry = coast.Altimetry(file_path='./example_files/COAsT_example_altimetry_data.nc',config='./config/example_altimetry.json')

# Inspect object
#$ altimetry.dataset

profile = coast.Profile(file_path='./example_files/EN4_example.nc', config='./config/example_en4_profiles.json') 

# Inspect object
#$ profile.dataset

# GLider data https://linkedsystems.uk/erddap/files/Public_Glider_Data_0711/Doombar_20210214/Doombar_553_R.nc
# More gliders downloadable at https://www.bodc.ac.uk/data/bodc_database/gliders/
glider = coast.Glider(file_path=dir + "Bellatrix_555_R.nc", config='./config/example_glider_ego.json')

# Inspect object
#$ glider.dataset

argos = coast.Argos(file_path=dir + 'ARGOS.CSV',config='./config/example_argos.json')

# Inspect object
#$ argos.dataset

oceanparcels = coast.Oceanparcels(file_path= dir + 'OceanParcels_GFDL-ESM2M.2043r3.1.nc',config='./config/example_oceanparcels.json') 

# Inspect object
#$ oceanparcels.dataset

import datetime 
date0 = datetime.datetime(2007,1,10) 
date1 = datetime.datetime(2007,1,12) 

tidegauge = coast.Tidegauge(file_path='./example_files/tide_gauges/lowestoft-p024-uk-bodc', date_start = date0, date_end = date1, config='./config/example_tidegauge.json') 

# Inspect object
#$ tidegauge.dataset
```

**Comment by jpolton** [comment]
@qtl-bodc All looks good. I made a script from your ticket comment to remind us about www documentation for another time.
There are some GitHub Actions tests that are failing. Didn't get a chance to properly diagnose.

**Comment by qtl-bodc** [comment]
@jpolton thanks nice to know. The failing github actions are related to the test script in tests/test_index_classes_load_datasets.py. Github finds the dataset paths in the test script invalid, i.e. file not found exception. Will be up to the User to ammend the filepaths or for us to gather up some sample datasets and provide them in the deployment package?

**Comment by jpolton** [comment]
> @jpolton thanks nice to know. The failing github actions are related to the test script in tests/test_index_classes_load_datasets.py. Github finds the dataset paths in the test script invalid, i.e. file not found exception. Will be up to the User to ammend the filepaths (to point to relevant datasets on their systems) or for us to gather up some sample datasets and provide them in the deployment package?

@qtl-bodc Ah! I see. No this is a known issue. The unit_testing helps us get around this problem since, in general, the test data are too large to host in a  place that is accessible to Git Actions. We need to move your tests into `unit_test2.py` and update 'unit_test_contents.txt'. I'll look at it now.

**Comment by jpolton** [comment]
@qtl-bodc  This pull request breaks the `unit_test2.py`. I.e.

On develop
```
#ipython
run unit_testing/unit_test2.py
```
returns:

```
1a OK - Nemo data loaded: Coast_example_NEMO_data.nc
/Users/jeff/GitHub/COAsT/coast/logging_util.py:78: UserWarning: /Users/jeff/GitHub/COAsT/coast/gridded.py._setup_grid_obj.77: No NEMO domain specified, only limited functionality will be available
  return warnings.warn(add_info(msg), *args, **kwargs)
1b OK - Coast.load_dataset()
1c OK - variable name reset (to temperature)
1d OK - dimension names reset
1e OK - Nemo loaded domain data only
1f OK - Nemo depth_0 calculations correct
1g OK - Nemo data subset loaded  with correct coords: Coast_example_NEMO_subset_data.nc
1h OK - Nemo data loaded combine  over time: nemo_data_T_grid*.nc
1i OK - Harmonics loaded and combined
1j OK - Harmonics converted
1k OK - computed e3[t,u,v,f,w] as expected
2a OK - Copied Coast object 
2b OK - Coast.__getitem__ works correctly 
2c OK - Renaming of variable in dataset 
2d OK - day of the week method
3a OK - Nemo.differentiate (for d/dz) method passes all tests
...
```
Not breaking the unit testing is a prerequisite for merging.

This pull request has broken something with the new config parser:
```
 run unit_testing/unit_test2.py
1a FAILED
1b FAILED
1c FAILED
1d FAILED
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/GitHub/COAsT/unit_testing/unit_test2.py in <module>
    191 
    192 pass_test = False
--> 193 nemo_f = coast.Gridded(fn_domain=dn_files + fn_nemo_dom, config=json_config_file_f_grid)
    194 
    195 if nemo_f.dataset._coord_names == {"depth_0", "latitude", "longitude"}:

~/GitHub/COAsT/coast/gridded.py in __init__(self, fn_data, fn_domain, multiple, config, workers, threads, memory_limit_per_worker, **kwargs)
     42 
     43         if path_lib.isfile(config):
---> 44             self.config = ConfigParser(config).config
     45             if self.config.chunks:
     46                 self._setup_grid_obj(self.config.chunks, multiple, **kwargs)

~/GitHub/COAsT/coast/config/config_parser.py in __init__(self, json_path)
     20             conf_type = ConfigTypes(json_content[ConfigKeys.TYPE])
     21             if conf_type == ConfigTypes.GRIDDED:
---> 22                 self.config = ConfigParser._parse_gridded(json_content)
     23             elif conf_type == ConfigTypes.INDEXED:
     24                 self.config = ConfigParser._parse_indexed(json_content)

~/GitHub/COAsT/coast/config/config_parser.py in _parse_gridded(json_content)
     35         proc_flags = json_content[ConfigKeys.PROC_FLAGS]
     36         chunks = json_content[ConfigKeys.CHUNKS]
---> 37         dataset = ConfigParser._get_datafile_object(json_content, ConfigKeys.DATASET)
     38         static_variables = ConfigParser._get_code_processing_object(json_content)
     39         try:

~/GitHub/COAsT/coast/config/config_parser.py in _get_datafile_object(json_content, data_file_type)
     95 
     96         if data_file_type is ConfigKeys.DATASET:
---> 97             dataset_coord_vars = dataset_json[ConfigKeys.COO_VAR]
     98             return Dataset(
     99                 variable_map=dataset_var,

KeyError: 'coord_vars'
```

**Review by jpolton — CHANGES_REQUESTED** [review]
@thogar-computer's `unit_test2.py` is broken by this pull request. See above comment.

**Comment by jpolton** [comment]
> @thogar-computer's `unit_test2.py` is broken by this pull request. See above comment.

It is because the format of the config file has changed. I am working on a fix for `unit_test2.py`

**Comment by jpolton** [comment]
> @qtl-bodc This pull request breaks the `unit_test2.py`. I.e.
> 
> On develop
> 
> ```
> #ipython
> run unit_testing/unit_test2.py
> ```
> 
> returns:
> 
> ```
> 1a OK - Nemo data loaded: Coast_example_NEMO_data.nc
> /Users/jeff/GitHub/COAsT/coast/logging_util.py:78: UserWarning: /Users/jeff/GitHub/COAsT/coast/gridded.py._setup_grid_obj.77: No NEMO domain specified, only limited functionality will be available
>   return warnings.warn(add_info(msg), *args, **kwargs)
> 1b OK - Coast.load_dataset()
> 1c OK - variable name reset (to temperature)
> 1d OK - dimension names reset
> 1e OK - Nemo loaded domain data only
> 1f OK - Nemo depth_0 calculations correct
> 1g OK - Nemo data subset loaded  with correct coords: Coast_example_NEMO_subset_data.nc
> 1h OK - Nemo data loaded combine  over time: nemo_data_T_grid*.nc
> 1i OK - Harmonics loaded and combined
> 1j OK - Harmonics converted
> 1k OK - computed e3[t,u,v,f,w] as expected
> 2a OK - Copied Coast object 
> 2b OK - Coast.__getitem__ works correctly 
> 2c OK - Renaming of variable in dataset 
> 2d OK - day of the week method
> 3a OK - Nemo.differentiate (for d/dz) method passes all tests
> ...
> ```
> 
> Not breaking the unit testing is a prerequisite for merging.
> 
> This pull request has broken something with the new config parser:
> 
> ```
>  run unit_testing/unit_test2.py
> 1a FAILED
> 1b FAILED
> 1c FAILED
> 1d FAILED
> ---------------------------------------------------------------------------
> KeyError                                  Traceback (most recent call last)
> ~/GitHub/COAsT/unit_testing/unit_test2.py in <module>
>     191 
>     192 pass_test = False
> --> 193 nemo_f = coast.Gridded(fn_domain=dn_files + fn_nemo_dom, config=json_config_file_f_grid)
>     194 
>     195 if nemo_f.dataset._coord_names == {"depth_0", "latitude", "longitude"}:
> 
> ~/GitHub/COAsT/coast/gridded.py in __init__(self, fn_data, fn_domain, multiple, config, workers, threads, memory_limit_per_worker, **kwargs)
>      42 
>      43         if path_lib.isfile(config):
> ---> 44             self.config = ConfigParser(config).config
>      45             if self.config.chunks:
>      46                 self._setup_grid_obj(self.config.chunks, multiple, **kwargs)
> 
> ~/GitHub/COAsT/coast/config/config_parser.py in __init__(self, json_path)
>      20             conf_type = ConfigTypes(json_content[ConfigKeys.TYPE])
>      21             if conf_type == ConfigTypes.GRIDDED:
> ---> 22                 self.config = ConfigParser._parse_gridded(json_content)
>      23             elif conf_type == ConfigTypes.INDEXED:
>      24                 self.config = ConfigParser._parse_indexed(json_content)
> 
> ~/GitHub/COAsT/coast/config/config_parser.py in _parse_gridded(json_content)
>      35         proc_flags = json_content[ConfigKeys.PROC_FLAGS]
>      36         chunks = json_content[ConfigKeys.CHUNKS]
> ---> 37         dataset = ConfigParser._get_datafile_object(json_content, ConfigKeys.DATASET)
>      38         static_variables = ConfigParser._get_code_processing_object(json_content)
>      39         try:
> 
> ~/GitHub/COAsT/coast/config/config_parser.py in _get_datafile_object(json_content, data_file_type)
>      95 
>      96         if data_file_type is ConfigKeys.DATASET:
> ---> 97             dataset_coord_vars = dataset_json[ConfigKeys.COO_VAR]
>      98             return Dataset(
>      99                 variable_map=dataset_var,
> 
> KeyError: 'coord_vars'
> ```

fixed

**Comment by jpolton** [comment]
> @thogar-computer's `unit_test2.py` is broken by this pull request. See above comment.

fixed

**Comment by davbyr** [comment]
index now inherits from coast. Fixing the problem with 5c

**Comment by davbyr** [comment]
Section 6 unit tests fixed

**Comment by jpolton** [comment]
On livljobs8
`ipython`:

```run unit_testing/unit_test.py```

works and all the original example_scripts working too.

**Review by jpolton — APPROVED** [review]
All issues fixed. `unit_testing.py` functionality restored

**Pull request merged**
