### PR TITLE
Add tidetable reading and processing

### PR DESCRIPTION
**Pull request by jpolton**
Add new header read and data load methods for tabulated HT and LT data. This might seem a bit off piste but it means I can integrate other workflows through COAsT to support its development.

Added a few bespoke methods:
1) to extract data from around a specified time
  get_tidetabletimes(self, time_guess:np.datetime64 = None, method: str='window', winsize:int=2)
  * method='window', winsize=6  -- search for values in +/- 6hrs window
  * method='nearest_1' -- find the nearest value (High or Low)
  * method='nearest_2' -- find nearest two values (a High and a Low)
  * method='nearest_HT' -- find the nearest high tide.

2) Prints out the data all nice. And includes a timezone shift if specified.
  show()

I've added a tutorial script and unit testing for all the key features.
There is a very small `example_files` file that is needed to make sure it works. Getting this onto the  ERDAP server will be a new ticket (incase there are changes to be made first).

AC:
- [ ] Put the file in your example_scripts
[Gladstone_2020-10_HLW.txt](https://github.com/British-Oceanographic-Data-Centre/COAsT/files/5393141/Gladstone_2020-10_HLW.txt)
- [ ] unit_testing works, including 9a which includes the new tutorial
- [ ] you are happy with it

*UPDATE* I am not sure how well my new methods (above) will interact with the GESLA data. Hmm.

### CODE REVIEW

**Comment by davbyr** [comment]
@jpolton Not checked the unit test yet (will do in the morning), but is this meant to be merged into master?

**Comment by jpolton** [comment]
> @jpolton Not checked the unit test yet (will do in the morning), but is this meant to be merged into master?

No it was not! Thanks. The target is now `develop`

**Review by davbyr — APPROVED** [review]
Looks great to me @jpolton. I've tested it with gesla data. .show() works:
```
time (UTC): Thu 2007-01-11T19:45 height: 2.1 m
time (UTC): Thu 2007-01-11T20:00 height: 2.192 m
time (UTC): Thu 2007-01-11T20:15 height: 2.278 m
time (UTC): Thu 2007-01-11T20:30 height: 2.334 m
time (UTC): Thu 2007-01-11T20:45 height: 2.421 m
time (UTC): Thu 2007-01-11T21:00 height: 2.497 m
```
`get_tidetabletimes()` doesn't crash for and gives sensible looking output for 3/4 of the methods but it isnt correct in the case of `nearest_HT`. Maybe a quick note in the docstring just to mention this?

I envisage one day there being that `TIMESERIES()` object, holding all the methods for general time series then `TIDEGAUGE` and `TIDETABLE` objects for more bespoke methods.

**Review by anwiseNOCL — COMMENTED** [review]
Maybe I missed something but the unit test fails on 7i and 9a but i also get:
9. Example script testing
++++++++++++++++++++++++
load and plot HLW data
time (Europe/London): Sun 2020-10-11T12:53+0100 height: 3.82 m
time (Europe/London): Sun 2020-10-11T18:52+0100 height: 7.33 m
time (Europe/London): Mon 2020-10-12T01:56+0100 height: 3.42 m
time (Europe/London): Mon 2020-10-12T07:45+0100 height: 7.38 m
time (Europe/London): Mon 2020-10-12T14:27+0100 height: 3.47 m
time (Europe/London): Mon 2020-10-12T20:18+0100 height: 7.78 m
time (Europe/London): Tue 2020-10-13T03:13+0100 height: 2.8 m
time (Europe/London): Tue 2020-10-13T08:59+0100 height: 8.01 m
time (Europe/London): Tue 2020-10-13T15:36+0100 height: 2.83 m
time (Europe/London): Tue 2020-10-13T21:21+0100 height: 8.45 m
time (Europe/London): Wed 2020-10-14T04:16+0100 height: 2.08 m
time (Europe/London): Wed 2020-10-14T09:54+0100 height: 8.71 m
time (Europe/London): Wed 2020-10-14T16:34+0100 height: 2.16 m

Not sure if this is how it is meant to be or not?

**Comment by anwiseNOCL** [comment]
Ok now I get:

run 'unit_testing/unit_test.py'
1a OK - NEMO data loaded: COAsT_example_NEMO_data.nc
/vkamino/work/anwise/python/COAsT/coast/logging_util.py:87: UserWarning: /vkamino/work/anwise/python/COAsT/coast/NEMO.py.__init__.38: No NEMO domain specified, only limited functionality will be available
  return warnings.warn(add_info(msg), *args, **kwargs)
1b OK - COAsT.load_dataset()
1c OK - variable name reset (to temperature)
1d OK - dimension names reset
1e OK - NEMO loaded domain data only
1f OK - NEMO depth_0 calculations correct
1g OK - NEMO data subset loaded  with correct coords: COAsT_example_NEMO_subset_data.nc
1h OK - NEMO data loaded combine  over time: nemo_data_T_grid*.nc
2a OK - Copied COAsT object 
2b OK - COAsT.__getitem__ works correctly 
2c OK - Renaming of variable in dataset 
2d OK - day of the week method
3a OK - NEMO.differentiate (for d/dz) method passes all tests
3b OK - Density correct
3c OK - pyncocline depth and thickness good



Figures now render in the Plots pane by default. To make them also appear inline in the Console, uncheck "Mute Inline Plotting" under the Plots pane options menu. 


 3d OK - pycnocline depth plot saved
4a OK - NEMO transect indices extracted
4b OK - TRANSECT cross flow calculations as expected
4c OK - TRANSECT velocity and transport plots saved
4d OK - TRANSECT density and pressure calculations as expected
4e OK - TRANSECT geostrophic flow calculations as expected
5a OK - NEMO COAsT get_subset_as_xarray extracted expected array size and extreme values
5b OK - NEMO domain subset_indices_by_distance extracted expected size of indices
5c OK - nearest_xy_indices works 
5d OK - Space interpolation works 
5e OK - Time interpolation works 
6a OK - Altimetry data loaded: COAsT_example_altimetry_data.nc
6b OK - ALTIMETRY object subsetted using isel 
6c OK - model SSH interpolated to altimetry
6d OK - Altimetry CRPS
6e OK - Basic Stats for ALTIMETRY
6f OK - Altimetry quick plot saved
7a OK - Tide gauge loaded
7b OK - Tide gauge obs_operator
7c OK - CRPS between gauge and model exists
7d OK - Basic Stats for TIDEGAUGE
7e OK - TIDEGAUGE resampled
7f OK - TIDEGAUGE doodson X0
7g OK - Multiple tide gauge load
7h OK - Tide gauge map plot saved
7i OK - Tide gauge multiple map plot saved
7j OK - Tide gauge time series saved
Not expecting that option / method
7k FAILED.
8a OK - Isobath contour extracted
8b OK - Contour plot saved
8c OK - Perturbation pressure calculation is as expected
8d OK - Cross-contour flow calculations as expected
8e OK - Cross-contour geostrophic flow calculations as expected
9. Example script testing
++++++++++++++++++++++++
load and plot HLW data
Try the TIDEGAUGE.show() method:
time (Europe/London): Tue 2020-10-13T03:13+0100 height: 2.8 m
time (Europe/London): Tue 2020-10-13T08:59+0100 height: 8.01 m
time (Europe/London): Tue 2020-10-13T15:36+0100 height: 2.83 m
time (Europe/London): Tue 2020-10-13T21:21+0100 height: 8.45 m
Try the TIDEGAUGE.get_tidetabletimes() methods:
9a FAILED.

**Pull request merged**
