### PR TITLE
Rework and refactor Markdown docs building.

### PR DESCRIPTION
**Pull request by MCazaly**
I'm not a huge fan of the solution we're using, but I've cleaned up our usage of it a little.

### CODE REVIEW

**Comment by MCazaly** [comment]
@thogar-computer  See [COAsT-site#61](https://github.com/British-Oceanographic-Data-Centre/COAsT-site/pull/61).

**Comment by thogar-computer** [comment]
Do we know what this was failing on the GitHub action and passing locally?

**Comment by MCazaly** [comment]
> Do we know why this was failing on the GitHub action and passing locally?

Not really. Best guess is that it's a difference between how subprocesses are handled on Windows VS Linux. Maybe PATH isn't inherited in the same way?

**Comment by MCazaly** [comment]
At any rate, this runs locally for me, so _should_ work in the pipeline too.

**Review by thogar-computer — APPROVED** [review]

**Pull request merged**
