### PR TITLE
permit loading of NEMO data that is a subset of the domain data

### PR DESCRIPTION
**Pull request by jpolton**
I've made a unit test example that loads AMM60 North Sea data and the whole AMM60 domain dataset. To work it needs to be able to see data on /projectsa

**COAsT.py**
* Trivial fix to get multi loads working

**NEMO.py**
* The changes only affects how the NEMO and domain objects are loaded and preprocessed.
* I added a **kwargs to the ``NEMO.py  __init__`` method. This is a bit clumsy but allowed me to pass a variable that was missing from my ``mesh_mask.nc`` that would have been in ``domain_cfg.nc``. E.g. ln_sco =1. _However the requirement that ln_sco=1 has been stripped, but something will come back when someone tries to process z-level global ORCA, or something_.
* The changes to Anthony's updates are: keep the computation of depth inside the dataset_domain object. This is because array size trimming is done once and two sets of array sizes can't exist in the same xr.DataSet (I chose to compute the depths before trimming). Because the depth variable is computed inside dataset_domain I also kept its name (deptht_0, depthw_0 etc) until is was copied to the NEMO object.
* Added tmask variable to the grid_vars keys. Not a very elegant solution to added extra variables

**unit test**
* The unit test modifications are only invoked if you can see the AMM60 files on /projectsa
* Do test for multi load
* Do test for subregion loading

**TRANSECT.py**
* Permit unspecified nemo_[UVT]

**CAVEAT** This pull/merge request spans an event where Tom did a rescue reset on develop. I think this messed up the history a bit. Consequently it looks like I am proposing changes that are already in develop. I think that the end result will be the same... 

AC: 
* run unit_test.py. In particular get success from **"1h and 1i"**

### CODE REVIEW

**Comment by jpolton** [comment]
I think your changes look OK for this ticket. I will update my code after you merge.

**Comment by jpolton** [comment]
@anwiseNOCL @davbyr Review request bump.

**Comment by davbyr** [comment]
@jpolton Had some initial confusion because I installed the CSIRO seawater package not the Gibb one.

I had to redownload the original example data for the unit_test to work. Was getting a familiar error beforehand:

```
[Errno -51] NetCDF: Unknown file format: b'/Users/Dave/Documents/Projects/WCSSP/COAsT/example_files/COAsT_example_NEMO_data.nc'
```
It works with the redownloaded data. Getting the branch from remote seems to overwrite these files though (if file names are the same), breaking the unit_test script.

**Comment by jpolton** [comment]
> @jpolton Had some initial confusion because I installed the CSIRO seawater package not the Gibb one.
> 
> I had to redownload the original example data for the unit_test to work. Was getting a familiar error beforehand:
> 
> ```
> [Errno -51] NetCDF: Unknown file format: b'/Users/Dave/Documents/Projects/WCSSP/COAsT/example_files/COAsT_example_NEMO_data.nc'
> ```
> 
> It works with the redownloaded data. Getting the branch from remote seems to overwrite these files though (if file names are the same), breaking the unit_test script.

I think we still have git-lfs stuff lurking in our filesystems. Having to re-download the `example_files` is no bad thing. However the checkout overwriting these files was bad. I have manually deleted all the netCDF files from `example_files` in the branch (to me they were invisible git-lfs links). Hopefully that has fixed it?

**Pull request merged**
