### PR TITLE
Develop --> Master

### PR DESCRIPTION
**Pull request by jpolton**
Attempt to merge all the develop goodness onto master.

The checks break because of an issue with 'dask'. This sounds familiar. @matt-caz can you remember what the fix was?

NB Incase it causes a subsequent problems, I have stripped out the git-lfs stuff, but I know how to fix that

### CODE REVIEW

**Comment by jpolton** [comment]
For some reason our attempts to merge develop into master had a step where master is merged into develop. That when things went bad. 
I can't figure out how to revert develop back to #105

**Comment by davbyr** [comment]
Hm, can we use `git revert`? @jpolton 

https://www.datree.io/resources/git-undo-merge

**Comment by jpolton** [comment]
> Hm, can we use `git revert`? @jpolton
> 
> https://www.datree.io/resources/git-undo-merge

I had trouble with revert. Try it...

**Comment by thogar-computer** [comment]
so i can do this locally via gitkarken (https://www.gitkraken.com/)

**Comment by thogar-computer** [comment]
image

**Comment by jpolton** [comment]
@thogar-computer gitkraken looks cool (indeed anything with an octopus on is obviously cool) but I can't figure out how to get the changes back onto remote. I think that there is badness lurking because of tampering with git-lfs.

If you can push a button and make it work then please do. I will not get a chance to look at this again until tomorrow afternoon.

**Comment by thogar-computer** [comment]
done :)

**Comment by jpolton** [comment]
Auto building the conda package on `master` got snagged in the build process.

I tried for a manual release [version upgrade]( https://github.com/British-Oceanographic-Data-Centre/COAsT/commit/1089cc370f23dc4ea88d11b087f37c559b2282ae ). Though that did progress the solution, a new problem emerged with [import yaml]( https://github.com/British-Oceanographic-Data-Centre/COAsT/runs/871083666?check_suite_focus=true ) during the build. 

So I stopped tampering incase I was making things worse

**Comment by jpolton** [comment]
Merge of `develop` onto `master` worked.

Auto building the conda package got snagged in the build process.

I tried for a manual release [version upgrade]( https://github.com/British-Oceanographic-Data-Centre/COAsT/commit/1089cc370f23dc4ea88d11b087f37c559b2282ae ) and though that did progress the solution, a new problem emerged with [import yaml](https://github.com/British-Oceanographic-Data-Centre/COAsT/runs/871083666?check_suite_focus=true)

I thought it was time to stop incase I was making things worse...

**Pull request merged**
