### PR TITLE
0161/transect restructure

### PR DESCRIPTION
**Pull request by anwiseNOCL**
Transect has been restructured to follow that used in the Contour code. This means that there is now a parent Transect class and child classes on specific grids. 
So usage is
```
tran_f = coast.Transect_f( nemo_f, (54,-15), (56,-12) )    
tran_f.calc_flow_across_transect( nemo_u,nemo_v )
tran_f.calc_geostrophic_flow( nemo_t )
tran_t = coast.Transect_t( nemo_t, (54,-15), (56,-12) )
tran_t.construct_pressure()
```
Other than that it is mainly internal tweaks and I have made some changes to optimise the code and it is significantly quicker now. Also I updated the unit testing for Transect stuff. 

Closes ticket #188

### CODE REVIEW

**Review by davbyr — APPROVED** [review]
Unit_test works fine for me. It's definitely good to have consistency across these sorts of objects

**Review by jpolton — COMMENTED** [review]
Does a tran_w transect object need special consideration?
I need to check the example_scripts and propose mods.

**Review by jpolton — CHANGES_REQUESTED** [review]
created a pull request to maintain compatibility with INTERNALTIDES and `internal_tide_pycnocline_diagnostics.py`

Happy for merge.

**Review by jpolton — APPROVED** [review]
I committed my merge to your branch by mistake..

**Pull request merged**
