### PR TITLE
Feature/code review rob

### PR DESCRIPTION
**Pull request by lukegorman**

### CODE REVIEW

**Comment by jpolton** [comment]
I know you didn't ask but I had a look anyway and ran unit_testing on the branch as is:
```
/Users/jeff/GitHub/COAsT/unit_testing/unit_test.py
test_gridded_calculate_bathymetry_for_f (test_gridded_initialisation.test_gridded_initialisation) ... ERROR
test_gridded_calculate_bathymetry_for_t (test_gridded_initialisation.test_gridded_initialisation) ... ERROR
test_gridded_calculate_bathymetry_for_u (test_gridded_initialisation.test_gridded_initialisation) ... ERROR
test_gridded_calculate_bathymetry_for_v (test_gridded_initialisation.test_gridded_initialisation) ... ERROR
test_gridded_calculate_depth0_for_tuvwf (test_gridded_initialisation.test_gridded_initialisation) ... ok
test_gridded_compute_e3_from_ssh (test_gridded_initialisation.test_gridded_initialisation) ... ok
test_gridded_load_dimensions_correctly_renamed (test_gridded_initialisation.test_gridded_initialisation) ... ok
test_gridded_load_domain_only (test_gridded_initialisation.test_gridded_initialisation) ... ok
test_gridded_load_multiple (test_gridded_initialisation.test_gridded_initialisation) ... 
...
```

**Comment by thogar-computer** [comment]
> I know you didn't ask but I had a look anyway and ran unit_testing on the branch as is:
> 
> ```
> /Users/jeff/GitHub/COAsT/unit_testing/unit_test.py
> test_gridded_calculate_bathymetry_for_f (test_gridded_initialisation.test_gridded_initialisation) ... ERROR
> test_gridded_calculate_bathymetry_for_t (test_gridded_initialisation.test_gridded_initialisation) ... ERROR
> test_gridded_calculate_bathymetry_for_u (test_gridded_initialisation.test_gridded_initialisation) ... ERROR
> test_gridded_calculate_bathymetry_for_v (test_gridded_initialisation.test_gridded_initialisation) ... ERROR
> test_gridded_calculate_depth0_for_tuvwf (test_gridded_initialisation.test_gridded_initialisation) ... ok
> test_gridded_compute_e3_from_ssh (test_gridded_initialisation.test_gridded_initialisation) ... ok
> test_gridded_load_dimensions_correctly_renamed (test_gridded_initialisation.test_gridded_initialisation) ... ok
> test_gridded_load_domain_only (test_gridded_initialisation.test_gridded_initialisation) ... ok
> test_gridded_load_multiple (test_gridded_initialisation.test_gridded_initialisation) ... 
> ...
> ```

are there any more detailed logs for these error messages? - all those tests are the ones I changed as part of my MR

**Comment by jpolton** [comment]
> > I know you didn't ask but I had a look anyway and ran unit_testing on the branch as is:
> > ```
> > /Users/jeff/GitHub/COAsT/unit_testing/unit_test.py
> > test_gridded_calculate_bathymetry_for_f (test_gridded_initialisation.test_gridded_initialisation) ... ERROR
> > test_gridded_calculate_bathymetry_for_t (test_gridded_initialisation.test_gridded_initialisation) ... ERROR
> > test_gridded_calculate_bathymetry_for_u (test_gridded_initialisation.test_gridded_initialisation) ... ERROR
> > test_gridded_calculate_bathymetry_for_v (test_gridded_initialisation.test_gridded_initialisation) ... ERROR
> > test_gridded_calculate_depth0_for_tuvwf (test_gridded_initialisation.test_gridded_initialisation) ... ok
> > test_gridded_compute_e3_from_ssh (test_gridded_initialisation.test_gridded_initialisation) ... ok
> > test_gridded_load_dimensions_correctly_renamed (test_gridded_initialisation.test_gridded_initialisation) ... ok
> > test_gridded_load_domain_only (test_gridded_initialisation.test_gridded_initialisation) ... ok
> > test_gridded_load_multiple (test_gridded_initialisation.test_gridded_initialisation) ... 
> > ...
> > ```
> 
> are there any more detailed logs for these error messages? - all those tests are the ones I changed as part of my MR

The parent `SE-NEMO` branch does not have these errors. Here is a log from running the first couple of tests only:
```
/Users/jeff/opt/anaconda3/envs/coast_dev/bin/python /Users/jeff/GitHub/COAsT/unit_testing/unit_test_tmp.py
test_gridded_calculate_bathymetry_for_f (test_gridded_initialisation.test_gridded_initialisation) ... ERROR
test_gridded_calculate_bathymetry_for_t (test_gridded_initialisation.test_gridded_initialisation) ... ERROR
test_gridded_calculate_bathymetry_for_u (test_gridded_initialisation.test_gridded_initialisation) ... ERROR
test_gridded_calculate_bathymetry_for_v (test_gridded_initialisation.test_gridded_initialisation) ... ERROR
test_gridded_calculate_depth0_for_tuvwf (test_gridded_initialisation.test_gridded_initialisation) ... ok
test_gridded_compute_e3_from_ssh (test_gridded_initialisation.test_gridded_initialisation) ... ok
test_gridded_load_dimensions_correctly_renamed (test_gridded_initialisation.test_gridded_initialisation) ... ok
test_gridded_load_domain_only (test_gridded_initialisation.test_gridded_initialisation) ... ok
test_gridded_load_multiple (test_gridded_initialisation.test_gridded_initialisation) ... ok
test_gridded_load_of_data_and_domain (test_gridded_initialisation.test_gridded_initialisation) ... ok
test_gridded_load_of_data_only (test_gridded_initialisation.test_gridded_initialisation) ... /Users/jeff/GitHub/COAsT/coast/_utils/logging_util.py:79: UserWarning: /Users/jeff/GitHub/COAsT/coast/data/gridded.py._setup_grid_obj.81: No NEMO domain specified, only limited functionality will be available
  return warnings.warn(add_info(msg), *args, **kwargs)
ok
test_gridded_load_subregion_with_domain (test_gridded_initialisation.test_gridded_initialisation) ... ok
test_gridded_load_variables_correctly_renamed (test_gridded_initialisation.test_gridded_initialisation) ... ok
test_bst_to_gmt (test_general_utils.test_general_utils) ... ok
test_coast_variable_renaming (test_general_utils.test_general_utils) ... ok
test_copy_coast_object (test_general_utils.test_general_utils) ... ok
test_day_of_week (test_general_utils.test_general_utils) ... ok
test_getitem (test_general_utils.test_general_utils) ... ok

======================================================================
ERROR: test_gridded_calculate_bathymetry_for_f (test_gridded_initialisation.test_gridded_initialisation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jeff/GitHub/COAsT/unit_testing/test_gridded_initialisation.py", line 123, in test_gridded_calculate_bathymetry_for_f
    nemo_f = coast.Gridded(fn_domain=files.fn_nemo_dom, config=files.fn_config_f_grid, calculate_bathymetry=True)
  File "/Users/jeff/GitHub/COAsT/coast/data/gridded.py", line 51, in __init__
    self._setup_grid_obj(None, multiple, **kwargs)
  File "/Users/jeff/GitHub/COAsT/coast/data/gridded.py", line 93, in _setup_grid_obj
    self.set_timezero_depths(
  File "/Users/jeff/GitHub/COAsT/coast/data/gridded.py", line 209, in set_timezero_depths
    bathymetry, mask, time_mask = self.calc_bathymetry(dataset_domain)
  File "/Users/jeff/GitHub/COAsT/coast/data/gridded.py", line 307, in calc_bathymetry
    bathymetry = np.array()
TypeError: array() missing required argument 'object' (pos 0)

======================================================================
ERROR: test_gridded_calculate_bathymetry_for_t (test_gridded_initialisation.test_gridded_initialisation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jeff/GitHub/COAsT/coast/data/gridded.py", line 209, in set_timezero_depths
    bathymetry, mask, time_mask = self.calc_bathymetry(dataset_domain)
  File "/Users/jeff/GitHub/COAsT/coast/data/gridded.py", line 303, in calc_bathymetry
    e3t = dataset_domain.e3t_0.squeeze()
  File "/Users/jeff/opt/anaconda3/envs/coast_dev/lib/python3.8/site-packages/xarray/core/common.py", line 256, in __getattr__
    raise AttributeError(
AttributeError: 'Dataset' object has no attribute 'e3t_0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jeff/GitHub/COAsT/unit_testing/test_gridded_initialisation.py", line 90, in test_gridded_calculate_bathymetry_for_t
    nemo_t = coast.Gridded(
  File "/Users/jeff/GitHub/COAsT/coast/data/gridded.py", line 49, in __init__
    self._setup_grid_obj(self.config.chunks, multiple, **kwargs)
  File "/Users/jeff/GitHub/COAsT/coast/data/gridded.py", line 93, in _setup_grid_obj
    self.set_timezero_depths(
  File "/Users/jeff/GitHub/COAsT/coast/data/gridded.py", line 214, in set_timezero_depths
    bathymetry = xr.zeros_like(dataset_domain.e1t.squeeze())
  File "/Users/jeff/opt/anaconda3/envs/coast_dev/lib/python3.8/site-packages/xarray/core/common.py", line 256, in __getattr__
    raise AttributeError(
AttributeError: 'Dataset' object has no attribute 'e1t'

======================================================================
ERROR: test_gridded_calculate_bathymetry_for_u (test_gridded_initialisation.test_gridded_initialisation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jeff/GitHub/COAsT/unit_testing/test_gridded_initialisation.py", line 101, in test_gridded_calculate_bathymetry_for_u
    nemo_u = coast.Gridded(
  File "/Users/jeff/GitHub/COAsT/coast/data/gridded.py", line 51, in __init__
    self._setup_grid_obj(None, multiple, **kwargs)
  File "/Users/jeff/GitHub/COAsT/coast/data/gridded.py", line 93, in _setup_grid_obj
    self.set_timezero_depths(
  File "/Users/jeff/GitHub/COAsT/coast/data/gridded.py", line 209, in set_timezero_depths
    bathymetry, mask, time_mask = self.calc_bathymetry(dataset_domain)
  File "/Users/jeff/GitHub/COAsT/coast/data/gridded.py", line 307, in calc_bathymetry
    bathymetry = np.array()
TypeError: array() missing required argument 'object' (pos 0)

======================================================================
ERROR: test_gridded_calculate_bathymetry_for_v (test_gridded_initialisation.test_gridded_initialisation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jeff/GitHub/COAsT/unit_testing/test_gridded_initialisation.py", line 112, in test_gridded_calculate_bathymetry_for_v
    nemo_v = coast.Gridded(
  File "/Users/jeff/GitHub/COAsT/coast/data/gridded.py", line 51, in __init__
    self._setup_grid_obj(None, multiple, **kwargs)
  File "/Users/jeff/GitHub/COAsT/coast/data/gridded.py", line 93, in _setup_grid_obj
    self.set_timezero_depths(
  File "/Users/jeff/GitHub/COAsT/coast/data/gridded.py", line 209, in set_timezero_depths
    bathymetry, mask, time_mask = self.calc_bathymetry(dataset_domain)
  File "/Users/jeff/GitHub/COAsT/coast/data/gridded.py", line 307, in calc_bathymetry
    bathymetry = np.array()
TypeError: array() missing required argument 'object' (pos 0)

----------------------------------------------------------------------
Ran 18 tests in 32.515s

FAILED (errors=4)

Process finished with exit code 0
```

**Comment by jpolton** [comment]
FYI unit testing on `develop` is still golden

**Comment by thogar-computer** [comment]
ok so we are getting different errors for different grids as the mapping process is not consistent between them 
``` shell
ERROR: test_gridded_calculate_bathymetry_for_t (test_gridded_initialisation.test_gridded_initialisation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jeff/GitHub/COAsT/coast/data/gridded.py", line 209, in set_timezero_depths
    bathymetry, mask, time_mask = self.calc_bathymetry(dataset_domain)
  File "/Users/jeff/GitHub/COAsT/coast/data/gridded.py", line 303, in calc_bathymetry
    e3t = dataset_domain.e3t_0.squeeze()
  File "/Users/jeff/opt/anaconda3/envs/coast_dev/lib/python3.8/site-packages/xarray/core/common.py", line 256, in __getattr__
    raise AttributeError(
AttributeError: 'Dataset' object has no attribute 'e3t_0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jeff/GitHub/COAsT/unit_testing/test_gridded_initialisation.py", line 90, in test_gridded_calculate_bathymetry_for_t
    nemo_t = coast.Gridded(
  File "/Users/jeff/GitHub/COAsT/coast/data/gridded.py", line 49, in __init__
    self._setup_grid_obj(self.config.chunks, multiple, **kwargs)
  File "/Users/jeff/GitHub/COAsT/coast/data/gridded.py", line 93, in _setup_grid_obj
    self.set_timezero_depths(
  File "/Users/jeff/GitHub/COAsT/coast/data/gridded.py", line 214, in set_timezero_depths
    bathymetry = xr.zeros_like(dataset_domain.e1t.squeeze())
  File "/Users/jeff/opt/anaconda3/envs/coast_dev/lib/python3.8/site-packages/xarray/core/common.py", line 256, in __getattr__
    raise AttributeError(
AttributeError: 'Dataset' object has no attribute 'e1t'
```
This error accords as @jpolton pointed out due to e3t_0 being remapped for all t-grid base files - it is hitting (and failing) on the first (code) line within `calc_bathymetry`

whereas the other errors 
```shell
ERROR: test_gridded_calculate_bathymetry_for_v (test_gridded_initialisation.test_gridded_initialisation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jeff/GitHub/COAsT/unit_testing/test_gridded_initialisation.py", line 112, in test_gridded_calculate_bathymetry_for_v
    nemo_v = coast.Gridded(
  File "/Users/jeff/GitHub/COAsT/coast/data/gridded.py", line 51, in __init__
    self._setup_grid_obj(None, multiple, **kwargs)
  File "/Users/jeff/GitHub/COAsT/coast/data/gridded.py", line 93, in _setup_grid_obj
    self.set_timezero_depths(
  File "/Users/jeff/GitHub/COAsT/coast/data/gridded.py", line 209, in set_timezero_depths
    bathymetry, mask, time_mask = self.calc_bathymetry(dataset_domain)
  File "/Users/jeff/GitHub/COAsT/coast/data/gridded.py", line 307, in calc_bathymetry
    bathymetry = np.array()
TypeError: array() missing required argument 'object' (pos 0)
```
pass the above line (`e3t = dataset_domain.e3t_0.squeeze()`) due to not having e3t_0 remapped, so the code moves on to the next problem which is the missing argument to `np.array()`

@jpolton has suggested setting bathymetry to;
`bathymetry = xr.zeros_like(bottom_level)`

**Comment by thogar-computer** [comment]
https://github.com/British-Oceanographic-Data-Centre/COAsT/pull/525 closes this pull request

**Pull request closed without merging**
