### PR TITLE
Feature/map domain vars

### PR DESCRIPTION
**Pull request by lukegorman**
add logic to map variable names in .nc to required names in code via json config

### CODE REVIEW

**Review by thogar-computer — COMMENTED** [review]
Looks good to me

**Comment by jpolton** [comment]
@roje-bodc @lukegorman I'm struggling here with
```
run unit_testing/unit_test.py
```
which is far from happy. Did you run this battery of tests against the datasets too, or just the GitAction tests?

**Comment by jpolton** [comment]
I believe the issues boil down to these:
```
test_gridded_load_domain_only (test_gridded_initialisation.test_gridded_initialisation) ... FAIL
test_gridded_load_subregion_with_domain (test_gridded_initialisation.test_gridded_initialisation) ... ERROR
```

**Comment by lukegorman** [comment]
> I believe the issues boil down to these:
> 
> ```
> test_gridded_load_domain_only (test_gridded_initialisation.test_gridded_initialisation) ... FAIL
> test_gridded_load_subregion_with_domain (test_gridded_initialisation.test_gridded_initialisation) ... ERROR
> ```

(coast_env) ➜  COAsT git:(feature/map_domain_vars) ✗ python unit_testing/unit_test.py
test_gridded_calculate_depth0_for_tuvwf (test_gridded_initialisation.test_gridded_initialisation) ... ok
test_gridded_compute_e3_from_ssh (test_gridded_initialisation.test_gridded_initialisation) ... ok
test_gridded_load_dimensions_correctly_renamed (test_gridded_initialisation.test_gridded_initialisation) ... ok
test_gridded_load_domain_only (test_gridded_initialisation.test_gridded_initialisation) ... ok

**Comment by lukegorman** [comment]
@jpolton please test this again :) and review the fix. Its a bit hacky but our brains could not find the fundamental issue.  

we dont like how depth_0 is handled and we are confused as to why its in the config.json at all given that it should not/ does not get mapped?

**Comment by anwiseNOCL** [comment]
> 



> @jpolton please test this again :) and review the fix. Its a bit hacky but our brains could not find the fundamental issue.
> 
> we dont like how depth_0 is handled and we are confused as to why its in the config.json at all given that it should not/ does not get mapped?

@lukegorman @jpolton The unit test runs fine now. The issue with depth_0 is that for certain domain_cfg.nc files the depth[ftuv] should get mapped to depth_0 (z levels model right jeff?) but for other domain_cfg.nc files that should be discarded and calculated manually (non-z-level models). As coast has evolved the whole depth_0 thing needs updating in my opinion. Maybe once the SE_NEMO branch is merged we can look into that.

**Review by jpolton — APPROVED** [review]
This is all good and ready to merge.

**Comment by jpolton** [comment]
> > @jpolton please test this again :) and review the fix. Its a bit hacky but our brains could not find the fundamental issue.
> > we dont like how depth_0 is handled and we are confused as to why its in the config.json at all given that it should not/ does not get mapped?
> 
> @lukegorman @jpolton The unit test runs fine now. The issue with depth_0 is that for certain domain_cfg.nc files the depth[ftuv] should get mapped to depth_0 (z levels model right jeff?) but for other domain_cfg.nc files that should be discarded and calculated manually (non-z-level models). As coast has evolved the whole depth_0 thing needs updating in my opinion. Maybe once the SE_NEMO branch is merged we can look into that.

New [ticket #524](https://github.com/British-Oceanographic-Data-Centre/COAsT/issues/524) started.

**Comment by roje-bodc** [comment]
This is all merged now 😎

**Pull request merged**
