### PR TITLE
0063

### PR DESCRIPTION
**Pull request by davbyr**
An update to the unit testing for copy (and other things):

1. Updated example files. They include more than just temperature (also ssh), and altimetry data is now there.

2. Updated unit_testing.py a little. Now includes copy() and crps_sonf(), although I don't think the tests are super rigorous. Struggling to automatically check that lazy loading is being preserved.

3. Updated unit_testing.py to have a bit more structure, which is outlined in unit_testing_contents.txt -- a new file.

### CODE REVIEW

**Comment by jpolton** [comment]
@davbyr @anwiseNOCL Is anyone else having issues with GitHub? My attempt to checkout 0063 fail fatally. Even a new clone of the repo does not work:

```
(base) [LIVMAP:~/GitHub] jeff% git clone https://github.com/British-Oceanographic-Data-Centre/COAsT.git tmp
Cloning into 'tmp'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 977 (delta 0), reused 1 (delta 0), pack-reused 973
Receiving objects: 100% (977/977), 66.30 MiB | 7.33 MiB/s, done.
Resolving deltas: 100% (532/532), done.
git-lfs filter-process: git-lfs: command not found
fatal: the remote end hung up unexpectedly
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

It might be a disk space issue. I do have some disk space on my machine but perhaps we have exceeded a GitHub bandwidth allowance?
Does anyone else have issues with ```git checkout 0063```?

**Comment by davbyr** [comment]
@jpolton @anwiseNOCL I'm not having that issue on livljobs. Clone and checkout seem to work as expected for me.

**Comment by jpolton** [comment]
@davbyr On both mac and livljobsN the error ```git-lfs filter-process: git-lfs: command not found``` is killing me. Did you do anything special to get ```git-lfs``` to work or be ignored (I'm not sure we use the git-lfs now). A short negative answer is welcome if true.

**Comment by davbyr** [comment]
@jpolton Weird... I've done nothing with LFS, especially on livljobs. Cloned the repository for the first time onto livljobs this morning to test Ant's problem with the example datasets. Then removed it and started again to test this..

Sorry not _that_ short.

**Comment by jpolton** [comment]
> @davbyr On both mac and livljobsN the error `git-lfs filter-process: git-lfs: command not found` is killing me. Did you do anything special to get `git-lfs` to work or be ignored (I'm not sure we use the git-lfs now). A short negative answer is welcome if true.

A bit weird but ```conda install git git-lfs``` to the conda environment did the job.

**Comment by davbyr** [comment]
@anwiseNOCL in the 0036 test script, the alt_attrs_ref dict is set to:

```
alt_attrs_ref = dict([('source', 'Jason-1 measurements'),
             ('date_created', '2019-02-20T11:20:56Z'),
             ('institution', 'CLS, CNES'),
             ('Conventions', 'CF-1.6'),])
```
Which should match the example file. Do you have an old version of the branch?

The warning messages come from using the set_command_variables(), which won't be needed in future I guess (or will be modified). But I did get these too.

**Comment by anwiseNOCL** [comment]
@davbyr Apparently I didn't! So what I learned is that when I checkout a purely remote branch I need to run a fetch first, otherwise any commits made since I last fetched will not be present. I guess you made that commit today? I'll understand git one day!

**Comment by davbyr** [comment]
Don't worry @anwiseNOCL, it's my fault. When I did the original pull request, I had forgotten to commit the final changes. I noticed yesterday morning and hoped I could sneak in the real branch before anyone noticed....

**Pull request merged**
