### PR TITLE
set_dimension_names and load file on init

### PR DESCRIPTION
**Pull request by davbyr**
@jpolton @anwiseNOCL This branch contains:

1. a new `set_dimension_names()` function inside COAsT (not the child classes). This is the dictionary iteration as discussed in the issue conversation.

2. a new `set_dimension_mapping()` function in COAsT and child classes. This is the function that sets the mapping dictionary.

The idea is that `set_dimension_names()` is called on load. It goes to the variable `self.dim_mapping` to rename dimensions. This is defined on initialisation (before load) in the `set_dimension_mapping()` method, which is kept in the child objects so it can be tailored appropriately. If it's not in a child object, the dictionary is `None` and nothing is renamed. A user can also redefine dimension names by simply putting a dictionary into `COAsT.set_dimension_names()`.

Also, some small changes to load functions:

3. There is now `load_multiple()` and `load_single()` functions inside COAsT, which do the same as before (`load_single` is as `load` was before). At the end of these functions, `set_dimension_names()` is called, so dimensions are renamed on load.

4. A new `load` function, which points to either `load_multiple()` or `load_single()` depending on whether the argument `multiple` is `True` or `False` (default False, so works as `load_single` does is not specified).

5. `load` is called as part of the initialisation, so filenames can be inputted when the object is first created. It will all still work as previously if filenames are input later on.

Do either of you know what the arguments in COAsT.__init__ are for and whether or not we can delete them? Specifically: `workers=2, threads=2, memory_limit_per_worker='2GB'` and the commented line:

```
# self.client = Client(n_workers=workers, threads_per_worker=threads, memory_limit=memory_limit_per_worker)
```

I've not updated unit_testing for this yet -- it does work though. Let me know what you think and I'll change it later.

### CODE REVIEW

**Comment by jpolton** [comment]
This looks great. 
Teseted with:

```
sci = COAsT.NEMO()
No file or directory specified: <coast.NEMO.NEMO object at 0x7f8bc9972290> 
Use COAsT.load() to load a netCDF file from file path or  directory into this object.

sci.load(dir + fn_nemo_dat)
Out[15]:
sci.dataset
<xarray.Dataset>
Dimensions:              (axis_nbounds: 2, t_dim: 7, x_dim: 297, y_dim: 375, z_dim: 51)...
```

and direct loading:

```
sci = COAsT.NEMO(dir + fn_nemo_dat)
sci.dataset
Out[16]: 
<xarray.Dataset>
Dimensions:              (axis_nbounds: 2, t_dim: 7, x_dim: 297, y_dim: 375, z_dim: 51)
Coordinates:
```

Also with domain file:
```
sci_dom = COAsT.DOMAIN()
No file or directory specified: <coast.DOMAIN.DOMAIN object at 0x7f8bc9961f50> 
Use COAsT.load() to load a netCDF file from file path or  directory into this object.

sci_dom.load(dir + fn_nemo_dom)
sci_dom.dataset
Out[14]: 
<xarray.Dataset>
Dimensions:       (t_dim: 1, x_dim: 297, y_dim: 375, z_dim: 51)
Dimensions without coordinates: t_dim, x_dim, y_dim, z_dim
```

And finally, with a view to updating the setting of variable names using a similar syntax:
``
sci.set_dimension_names({'z_dim':'z_dimension_with_a_long_name'})
``
Also works, though of course this method is hard wired for dimension names.

**Comment by jpolton** [comment]
> Do either of you know what the arguments in COAsT.init are for and whether or not we can delete them? Specifically: workers=2, threads=2, memory_limit_per_worker='2GB' and the commented line:
``` # self.client = Client(n_workers=workers, threads_per_worker=threads, memory_limit=memory_limit_per_worker)```

All I know is that that is to do with dask...

**Comment by davbyr** [comment]
@jpolton I've updated the branch to include a `set_variable_names()` method which basically works the same as set_dimension_names(). The two methods are so close that I'm wondering if they should be merged or if it is clearer the way it is...

unit_test.py will not work right now since it looks for dimensions that do not exist after renaming. So if we want to merge this into the package immediately, we will ahve to set the naming dictionaries to None for now.

**Comment by davbyr** [comment]
@jpolton @anwiseNOCL I've set all automatic renaming dictionaries to None for the time being, since renaming dimensions and variables breaks pretty much everything at the moment (until the rest of the code is changed to reflect this). When renaming dicts are None, the functions just do nothing, so the functionality can remain, just unused. This branch still allows for loading in init(), which is useful.

It would be good to get this functionality into the package even though I'm not updating unit_testing to reflect it. Are you both happy to merge this? It can be tested as follows:

Load on init():
```
sci = NEMO(fn_nemo)
```

Manual renaming:
```
sci.set_dimension_names({'x':'x_dim'})
sci.set_variable_names({'time_counter':'time'}
```
To test automatic renaming, you can uncomment the `set_dimension_mapping` and `set_variable_mapping` methods in NEMO and DOMAIN, then check the dataset.

At some point we will need to agree on conrete renaming rules and then coordinate the changing of variable/dimension references throughout the rest of the package.

**Pull request merged**
