### PR TITLE
remove deprec warning

### PR DESCRIPTION
**Pull request by soutobias**
After updating the Python version, there were still some deprecation warnings present in the code. I successfully addressed and resolved all of the warnings associated with the COAsT code. However, there remain certain warnings related to the xarray and utide libraries, which cannot be eliminated since they pertain to dependencies. I also chose to retain one warning labeled as "Pending" because I believe it may only become relevant in the distant future.

### CODE REVIEW

**Comment by soutobias** [comment]
This PR is related to these issues: https://github.com/British-Oceanographic-Data-Centre/COAsT/issues/629 and https://github.com/British-Oceanographic-Data-Centre/COAsT/issues/558

**Review by jpolton — APPROVED** [review]
Looks good. I've restored a matplotlib thing whereby the color scale broke for one of the unit testing figures.

**Comment by soutobias** [comment]
@jpolton , I fixed the cmap stuff and now it works. I also updated all github actions related to notebooks. An error occurred in the python version, as it was instantiated twice: in the workflow and in the environment.yml. So, I removed the workflow version for these tests.

**Comment by jpolton** [comment]
Great work. I'll merge it.

**Pull request merged**
