### PR TITLE
0087 place for scripts

### PR DESCRIPTION
**Pull request by jpolton**
# A template for use case examples

The science package examples will be run by scripts. Though these maybe lightweight wrappers to all the fancy object orientated programming, they will still need to exist. Indeed they could serve as useful entry points to demonstrate how to use the functionality.

Here I have created a new directory (at the same level as unit_testing and example_files to host scripts that invoke the package to achieve some diagnostic objective.

These scripts could form the basis of the html examples at:
 https://british-oceanographic-data-centre.github.io/COAsT/

See Issue: https://github.com/British-Oceanographic-Data-Centre/COAsT/issues/87

The example script was going to be my internal tides work but it really isn't fit for `develop` so I copied some of Dave's CRPS work, which might soon be out of date...

### CODE REVIEW

**Comment by davbyr** [comment]
@jpolton Just looking at this now. Did you intend to merge into Master or should it be develop?

**Comment by jpolton** [comment]
> @jpolton Just looking at this now. Did you intend to merge into Master or should it be develop?

Bother this should have been a merge into `develop` not `master`. Once @anwiseNOCL and @davbyr are both happy I will close this request and recreate as a merge into develop. I will merge then without asking seeking reviews.

**Comment by anwiseNOCL** [comment]
@jpolton @davbyr Is this using old versions of the example file? I get errors about unknown netcdf file format, which is what happened before dave updated the example files

**Comment by jpolton** [comment]
> @jpolton @davbyr Is this using old versions of the example file? I get errors about unknown netcdf file format, which is what happened before dave updated the example files

I will investigate!

**Comment by davbyr** [comment]
@anwiseNOCL I'm not sure, but I'm getting the same thing:

```
Errno -51] NetCDF: Unknown file format: b'/Users/Dave/Documents/Projects/WCSSP/COAsT/example_files/COAsT_example_NEMO_domain.nc'
```

The files look like the right ones to me. Could this be related to Jeff's Git-LFS problems?

**Pull request closed without merging**
