### PR TITLE
0624/polar quivers notebook

### PR DESCRIPTION
**Pull request by b-barton**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x ] Tests for the changes have been added (for bug fixes / features)
- [x ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
    - Some docs updates need to be made in the `COAsT-site` repo, in a separate PR. See [contributing to documentation ](https://british-oceanographic-data-centre.github.io/COAsT/docs/contributing-docs/) for details.
- [x ] Build (`./build.sh`) was run locally and no errors reported. NB not sure about this requirement: GitActions test this
- [x ] Lint (`pylint .`) has passed locally and any fixes were made for failures. NB not sure about this requirement: GitActions test this with `black`

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x ] Other (please describe): Example notebooks

## What is the current behavior?

Issue URL: #

## What is the new behavior?

New example notebooks for the Arctic domain. This shows how to plot quivers and use the functions to make adjustments for NEMO curvilinear grid and cartopy polar projection. An additional notebook has been added for plotting the new example dataset (a cropped version of a global NEMO run) for the Arctic. This includes plotting contours over the arctic which are not straight forward. Additional plotting helper functions have been added to plot_util for making polar plots and for plotting contours on polar plots. Tests included for these.
-
-
### Checklist
- [x ] Code compiles correctly
- [ ] Created tests which fail without the change (if possible)
- [~ ] All tests passing (`pip install . && pytest unit_testing/unit_test.py -s`)
Same as before there are two tests I'm unable to run on my machine "test_gridded_initialisation" and "test_tidegauge_methods" (Windows things). The rest passed. I have no reason to think test_gridded_initialisation or test_tidegauge_methods would fail. Git actions tests keeps failing but I'm not sure why.
- [ ] Extended the README / documentation, if necessary
- [x ] Added myself / the copyright holder to the AUTHORS file

## Does this introduce a breaking change?

- [ ] Yes
- [x ] No

### CODE REVIEW

**Comment by jpolton** [comment]
Hmmm. There is definitely a problem with installing cartopy on the GitAction runners. The problem looks like the containers are trying to install cartopy from source, which is hard. The internet recommends using conda to install cartopy. However, the runners use a `pip install` method that uses the  `requirements.txt` file. Perhaps it would be easier if the runners copied the environment.yml approach with slip pip and conda install methods? Hmmm

**Comment by jpolton** [comment]
Previously we installed cartopy but not pyproj. The problem now might be it is hard to mix these two packages as cartopy has pyproj under the hood...

**Comment by soutobias** [comment]
@jpolton @b-barton , I updated the codes, removed cartopy and includes pyproj instead. I also included some changes on the codes related to pylint. All tests are passing except from the pylint one. But I already updated the pylint one on another branch and it will solve this issue.

**Review by soutobias — APPROVED** [review]
Looks good for me

**Pull request merged**
