### PR TITLE
WIP: Add action to automatically apply Black formatting to Python code.

### PR DESCRIPTION
**Pull request by Fakas**
This also includes the addition of 3.9 support for package build/checks.

### CODE REVIEW

**Comment by Fakas** [comment]
Converted to draft as the line length setting does not appear to be working just yet.

**Comment by thogar-computer** [comment]
I can see a few changes to the code based on black formatting is this to do with the line length issue? as i though develop had already been blackened

**Review by qtl-bodc — COMMENTED** [review]
Looks good.

**Comment by Fakas** [comment]
Moved code to a fresh branch to clean up extraneous changes: https://github.com/British-Oceanographic-Data-Centre/COAsT/pull/306

**Pull request closed without merging**
