### PR TITLE
Conda auto-deploy

### LINKED ISSUE #37: Automatic conda publishing (BODCDMSYS-2187)
n the interest of reproducibility and reducing future maintenance overheads, we want to set up a GitHub Actions workflow to automate build and deployment of the COAsT package to Anaconda. We currently have the equivalent set up for PyPi deployment, so this will give us a complete setup. 

We'll probably want to include this functionality in the existing PyPi deployment workflow, so that if build or deployment to PyPi fail (for instance, when the version number hasn't been updated), then deployment to Anaconda won't happen. 

Given: We can automatically deploy the package to PyPi. 
When: The master branch is pushed to with a new version 
Then: The package is built and deployed to the BODC organisation on Anaconda Cloud. 

AC 

We have a functional workflow that automatically deploys to Anaconda Cloud on push to the master branch. 
UAC - Dave to check with some code changes of his own.

### LINKED ISSUE #130: Add `gsw` package to conda build
COAsT now uses the TEOS-10 python package which can be installed

``conda install -c conda-forge gsw``

Perhaps magic things need to be done to add this to a list for the automatic conda builds?

### PR DESCRIPTION
**Pull request by matt-caz**
This is largely already in master as a result of testing the publish pipeline, should still be reviewed.
Includes package requirements as outlined in #130 

Closes #37 
Closes #130

### CODE REVIEW

**Review by davbyr — APPROVED** [review]
Did the conda install in a new environment and checked the source code was up to date.

**Comment by jpolton** [comment]
Assuming I got the correct AC then this is good:

```
git checkout feature/conda
conda create -n tmp_16Sept20 python==3.7
conda activate tmp_16Sept20
conda install -c conda-forge -c bodc coast
```
Then
```
ipython
```

```
import COAsT                                                                                   
/Users/jeff/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:17: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
```
It works!

NB @matt-caz @davbyr @thogar-computer @anwiseNOCL :  ``import coast`` does not work because of the case sensitive nature. (So unit testing breaks on ``import coast``). I can not recall what we decided to do about this?

**Review by jpolton — APPROVED** [review]

**Comment by davbyr** [comment]
Sorry @matt-caz, I made a tiny change to master and pushed (a comment in TIDEGAUGE), but it is getting stuck at publishing to pypi:

Run ./publish.sh "https://upload.pypi.org/legacy/" "$PYPI_TOKEN"
Uploading distributions to https://upload.pypi.org/legacy/
Uploading COAsT-0.2.1a37-py3-none-any.whl

  0%|          | 0.00/42.5k [00:00<?, ?B/s]
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
File already exists. See https://pypi.org/help/#file-name-reuse for more information.
100%|██████████| 42.5k/42.5k [00:00<00:00, 179kB/s]
NOTE: Try --verbose to see response content.
##[error]Process completed with exit code 1.

I think we've had this one before? Was it a version number thing?

**Comment by Fakas** [comment]
@davbyr Yes, pushes to master require a version bump. Line 8 of setup.py is where to update it.

**Comment by matt-caz** [comment]
@davbyr Yes. Pushes to master require a version bump. Line 8 of setup.py is where to fix it.

**Comment by davbyr** [comment]
@matt-caz Cool, this works now 👍 

@jpolton @anwiseNOCL I have tested this by making a very small change to the master branch (added a '.' to the docstring of TIDEGAUGE). I pushed it to master. On github it successfully ran through all the automated procedures. Then I installed coast in a brand new conda environment, and the '.' is there.

**Review by thogar-computer — APPROVED** [review]
Looks good to me

**Pull request merged**
